import argparse
from socket import socket

from prompt_toolkit import prompt
from prompt_toolkit.completion import WordCompleter
import pyfiglet
import socket



def main():
    parser = argparse.ArgumentParser(description="W")
    parser.add_argument('-p', '--port', type=str, help='The temporary file generated by pytest-leaping', required=True)

    args = parser.parse_args()
    if not args.port:
        raise ValueError("Port number not provided. Exiting...")

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(('localhost', int(args.port)))


    commands_completer = WordCompleter(['exit', 'hello', 'help'], ignore_case=True)
    ascii_art = pyfiglet.figlet_format("Leaping")
    print(ascii_art)

    first_response = sock.recv(2048)
    print("\033[92mExplanation: " + first_response.decode("utf-8"))

    while True:
        user_input = prompt("\nIf the explanation is wrong, say why and we'll try again. Press q to exit: ")
        if user_input == "q":
            sock.sendall(b"exit")
            break
        sock.sendall(user_input.encode("utf-8"))
        response = sock.recv(2048)
        print(response.decode("utf-8"))
